version: '3.8'

services:
  # Основное Laravel-приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gatekeeper-app:latest
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-http://localhost}
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
    env_file:
      - .env.production
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - mysql
      - redis

  # MySQL 8.0
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306"
    restart: unless-stopped

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379"
    restart: unless-stopped

  # Nginx — веб-сервер
  nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./storage:/var/www/html/storage:ro
    depends_on:
      - app
    restart: unless-stopped

# Объявляем volume для БД
volumes:
  mysql_data: